### PR TITLE
Enable shellcheck

### PR DESCRIPTION
**Pull request by matttrach**

### CODE REVIEW

**Review by VestigeJ — COMMENTED** [review]
Do you need to check for processes using the targeted ports beforehand? It isn't likely an existing service will be running correct?

**Comment by matttrach** [comment]
yeah, I guess I was assuming that the server was made just for rke2 and not already running some workloads. Won't rke2 fail to install with some useful error if the port is used? This feels like something that the installer should be validating rather than Terraform.

**Comment by matttrach** [comment]
We are not specifying any ports in anything we do, we would have to parse the config to see if any ports were set there before we could do that, which seems like a lot of added complexity, we would also have to keep track of any changes to the config schema to make sure the format of the port string and placement of that value doesn't change. I would prefer to put this burden on the installer if possible.

**Comment by matttrach** [comment]
Either way, this PR is not about validating inputs, it is about extracting shell scripts and added a shell script linter to the CI.

**Pull request merged**
